language: ruby
rvm:
  - 2.1.2
before_script:
  - psql -c 'create database whovar_test;' -U postgres
  - 'cp config/database.travis.yml config/database.yml'
  - 'bundle exec rake db:setup'
script: 'RAILS_ENV=test bundle exec rake'
env:
  global:
    - DB=postgresql
    - secure: "Jf/AiQkwikcxU0SKtB8wQ4/ytEGknQfO/VjRrz2XVVptgcxm6TUNz6hiuhfvVIPY7ZUhAnd67qKMVBOk1Be0SKVNaGvlRAZyKKlmlfCGGjvIe18njJYKSC+DubbRco232ngze2dZ69jgidmaNbUIGK6ywx+HsFCR9lKgGT5mf3Q="
